[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "rust_maze_solver"
version = "0.1.0"
requires-python = ">=3.12.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "fastapi",
    "networkx",
    "matplotlib",
    "joblib",
]


[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "rust_maze_solver"
binding = "pyo3"
